"""
fusion/ir.py - Python IR for elementwise tensor expressions.

Each Expr node represents an elementwise scalar computation. Nodes are
purely declarative: they carry an AST-shaped description of a function
mapping one scalar input `x` to a scalar output `y`. They do NOT know
about tensors, shapes, strides, or devices.

Composition is recursive: `Add(Mul(x, 2.0), 3.0)` describes `x*2 + 3`,
mirroring the AST you would write by hand but built bottom-up from the
leaves.

Lowering to C++ / CUDA happens in `fusion.codegen` via `Expr.codegen()`,
which formats the AST into a C++ expression string consumable by nvcc.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Union, Type


# ---------------------------------------------------------------------------
# Base class
# ---------------------------------------------------------------------------


@dataclass
class Expr:
    """Base class for all IR nodes. Subclasses must override codegen()."""

    def codegen(self) -> str:
        raise NotImplementedError(f"{type(self).__name__}.codegen not implemented")


# ---------------------------------------------------------------------------
# Leaves
# ---------------------------------------------------------------------------


@dataclass
class Input(Expr):
    """Reference to the kernel's `x` scalar input.

    The codegen() returns the C++ identifier (`"x"`). All elementwise
    kernels generated by this IR operate on a single float loaded into
    a local `float x` per thread; multi-input kernels would require a
    richer IR (left as a future extension).
    """

    name: str = "x"

    def codegen(self) -> str:
        return self.name


@dataclass
class Const(Expr):
    """A float constant literal.

    Always lowers to a C++ float literal with the `f` suffix
    (e.g. `2.000000f`). Accepts both int and float; ints are widened
    to float to match the kernel's `float x` storage type and avoid
    nvcc implicit-conversion warnings.
    """

    value: float

    def __post_init__(self) -> None:
        # Normalise to float so codegen() can be a single branch.
        self.value = float(self.value)

    def codegen(self) -> str:
        # %.6f yields the canonical "2.000000f" form expected by tests.
        return f"{self.value:.6f}f"


# ---------------------------------------------------------------------------
# Binary ops
# ---------------------------------------------------------------------------


@dataclass
class Mul(Expr):
    """Multiplication of two subexpressions."""

    a: Expr
    b: Expr

    def codegen(self) -> str:
        return f"({self.a.codegen()} * {self.b.codegen()})"


@dataclass
class Add(Expr):
    """Addition of two subexpressions."""

    a: Expr
    b: Expr

    def codegen(self) -> str:
        return f"({self.a.codegen()} + {self.b.codegen()})"


# ---------------------------------------------------------------------------
# Unary activations
# ---------------------------------------------------------------------------


@dataclass
class Relu(Expr):
    """ReLU(x) = max(x, 0). Uses `fmaxf` for nvcc."""

    x: Expr

    def codegen(self) -> str:
        return f"fmaxf({self.x.codegen()}, 0.0f)"


@dataclass
class Sigmoid(Expr):
    """Sigmoid(x) = 1 / (1 + exp(-x))."""

    x: Expr

    def codegen(self) -> str:
        return f"(1.0f / (1.0f + expf(-({self.x.codegen()}))))"


@dataclass
class Tanh(Expr):
    """Tanh via the standard `tanhf` host/device intrinsic."""

    x: Expr

    def codegen(self) -> str:
        return f"tanhf({self.x.codegen()})"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "Expr",
    "Input",
    "Const",
    "Mul",
    "Add",
    "Relu",
    "Sigmoid",
    "Tanh",
]
