load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "mnist",
    srcs = ["MnistLoader.cpp"],
    hdrs = ["MnistLoader.hpp"],
    visibility = ["//visibility:public"],
    deps = ["//tensor:tensor_core"],
)

cc_test(
    name = "mnist_loader_test",
    srcs = ["mnist_loader_test.cpp"],
    deps = [":mnist", "//tensor:tensor_core", "//third_party/doctest:doctest"],
    tags = ["cpu"],
)

cc_library(
    name = "cifar",
    srcs = ["CifarLoader.cpp"],
    hdrs = ["CifarLoader.hpp"],
    visibility = ["//visibility:public"],
    deps = ["//tensor:tensor_core"],
)

cc_test(
    name = "cifar_loader_test",
    srcs = ["cifar_loader_test.cpp"],
    deps = [":cifar", "//tensor:tensor_core", "//third_party/doctest:doctest"],
    tags = ["cpu"],
)
